In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [19]:
df=pd.read_csv("Churn_Modelling.csv")
df.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [20]:
y=df.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [21]:
X=df.iloc[:,3:13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [22]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

# o for female and 1 for male
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2 .fit_transform(X[:,2])
X



array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [23]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [24]:
ct = ColumnTransformer([('State', OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [25]:
X=X[:,1:]

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
import keras
from  keras.models import Sequential
from keras.layers import Dense

In [33]:
classifier = Sequential()
classifier.add(Dense(output_dim=6 ,init ='uniform' ,activation='relu' ,input_dim =11))
classifier.add(Dense(output_dim=6 ,init ='uniform' ,activation='relu'))
classifier.add(Dense(output_dim=1 ,init ='uniform' ,activation='sigmoid'))
classifier.compile(optimizer='adam' ,loss='binary_crossentropy' ,metrics =['accuracy'])

C:\Users\gupta\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  
C:\Users\gupta\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\gupta\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  after removing the cwd from sys.path.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [34]:
classifier.fit(X_train ,y_train , batch_size=10 , nb_epoch=100)

C:\Users\gupta\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.



Epoch 1/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4904 - accuracy: 0.79 - 3s 403us/step - loss: 0.4895 - accuracy: 0.7958
Epoch 2/100
8000/8000 [==============================] - 3s 366us/step - loss: 0.4285 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 355us/step - loss: 0.4223 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 3s 347us/step - loss: 0.4183 - accuracy: 0.8201
Epoch 5/100
8000/8000 [==============================] - 2s 255us/step - loss: 0.4159 - accuracy: 0.8275
Epoch 6/100
8000/8000 [==============================] - 2s 260us/step - loss: 0.4140 - accuracy: 0.8303
Epoch 7/100
8000/8000 [==============================] - 2s 277us/step - loss: 0.4128 - accuracy: 0.8315
Epoch 8/100
8000/8000 [==============================] - 2s 267us/step - loss: 0.4117 - accuracy: 0.8324
Epoch 9/100
8000/8000 [==============================] - 2s 256us/step - loss: 0.4109 - accuracy: 0.8336
Epoch 10/100

8000/8000 [==============================] - 2s 280us/step - loss: 0.3946 - accuracy: 0.8360
Epoch 76/100
8000/8000 [==============================] - 2s 282us/step - loss: 0.3946 - accuracy: 0.8353
Epoch 77/100
8000/8000 [==============================] - 2s 286us/step - loss: 0.3948 - accuracy: 0.8357
Epoch 78/100
8000/8000 [==============================] - 3s 313us/step - loss: 0.3952 - accuracy: 0.8370
Epoch 79/100
8000/8000 [==============================] - 3s 314us/step - loss: 0.3946 - accuracy: 0.8363
Epoch 80/100
8000/8000 [==============================] - 2s 279us/step - loss: 0.3940 - accuracy: 0.8360
Epoch 81/100
8000/8000 [==============================] - 2s 266us/step - loss: 0.3941 - accuracy: 0.8365
Epoch 82/100
8000/8000 [==============================] - 2s 268us/step - loss: 0.3942 - accuracy: 0.8354
Epoch 83/100
8000/8000 [==============================] - 2s 273us/step - loss: 0.3938 - accuracy: 0.8371
Epoch 84/100
8000/8000 [==============================] - 2

In [36]:
y_pred = classifier.predict(X_test)
y_pred

array([[0.16455957],
       [0.36268693],
       [0.12733111],
       ...,
       [0.17631075],
       [0.10897565],
       [0.12580651]], dtype=float32)

In [37]:
y_pred=(y_pred > 0.5)

In [38]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [40]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)
cm

array([[1550,   45],
       [ 263,  142]], dtype=int64)